/**
 * Writes assets/js/config.js from SUPABASE_URL and SUPABASE_ANON_KEY.
 * Used locally and in CI — never commit assets/js/config.js.
 *
 * Local:  node --env-file=.env scripts/write-config.mjs
 *    or:  SUPABASE_URL=... SUPABASE_ANON_KEY=... node scripts/write-config.mjs
 */
import { writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, '..', 'assets', 'js', 'config.js');

export function generatePublicConfig(env = process.env) {
  const url = env.SUPABASE_URL?.trim();
  const key = env.SUPABASE_ANON_KEY?.trim();
  const gamesCatalogSource = (env.GAMES_CATALOG_SOURCE || 'json').trim().toLowerCase();

  if (!url || !key) {
    throw new Error(
      'Missing SUPABASE_URL or SUPABASE_ANON_KEY.\n' +
        'Set them in the environment or in a .env file and run:\n' +
        '  node --env-file=.env scripts/write-config.mjs'
    );
  }

  return `/* Generated by scripts/write-config.mjs — do not commit. */
window.SNH_CONFIG = {
  supabaseUrl: ${JSON.stringify(url)},
  supabaseAnonKey: ${JSON.stringify(key)},
  gamesCatalogSource: ${JSON.stringify(gamesCatalogSource === 'db' ? 'db' : 'json')},
};
`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    const contents = generatePublicConfig();
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, contents, 'utf8');
    console.log('Wrote', outPath);
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
