/**
 * Writes assets/js/config.js from SUPABASE_URL and SUPABASE_ANON_KEY.
 * Used locally and in CI — never commit assets/js/config.js.
 *
 * Local:  node --env-file=.env scripts/write-config.mjs
 *    or:  SUPABASE_URL=... SUPABASE_ANON_KEY=... node scripts/write-config.mjs
 */
import { writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, '..', 'assets', 'js', 'config.js');

const url = process.env.SUPABASE_URL?.trim();
const key = process.env.SUPABASE_ANON_KEY?.trim();
const gamesCatalogSource = (process.env.GAMES_CATALOG_SOURCE || 'json').trim().toLowerCase();

if (!url || !key) {
  console.error(
    'Missing SUPABASE_URL or SUPABASE_ANON_KEY.\n' +
      'Set them in the environment or in a .env file and run:\n' +
      '  node --env-file=.env scripts/write-config.mjs'
  );
  process.exit(1);
}

const contents = `/* Generated by scripts/write-config.mjs — do not commit. */
window.SNH_CONFIG = {
  supabaseUrl: ${JSON.stringify(url)},
  supabaseAnonKey: ${JSON.stringify(key)},
  gamesCatalogSource: ${JSON.stringify(gamesCatalogSource === 'db' ? 'db' : 'json')},
};
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, contents, 'utf8');
console.log('Wrote', outPath);
