-- Photos storage buckets: photos-private (originals + staging) and
-- photos-public (published derivatives). Tightly restrict storage.objects so
-- that no client role (anon, authenticated) can read photos-private or write
-- to either bucket directly. All authorized writes go through the photo
-- Edge Functions running as service_role.

insert into storage.buckets (id, name, public)
values
  ('photos-private', 'photos-private', false),
  ('photos-public',  'photos-public',  true)
on conflict (id) do update
  set public = excluded.public;

-- Public bucket is configured public=true so signed URLs are not required to
-- read derivatives; this is intentional and matches the architecture decision
-- in docs/photos-foundation.md. We rely on:
--   1. The Edge Function being the only writer (service role).
--   2. The DB layer treating photo_asset_variants rows as the source of truth
--      for what URLs are public.
--   3. Unpublish/delete actively removing objects from photos-public.

-- ---------------------------------------------------------------------------
-- storage.objects policies
-- ---------------------------------------------------------------------------

-- photos-private: NO read/write access for anon or authenticated.
-- service_role bypasses RLS, so the photo Edge Functions and signed URLs
-- generated by service_role still work. Removing any prior permissive
-- policies for safety.

drop policy if exists photos_private_anon_read on storage.objects;
drop policy if exists photos_private_authenticated_read on storage.objects;
drop policy if exists photos_private_authenticated_write on storage.objects;
drop policy if exists photos_private_authenticated_delete on storage.objects;
drop policy if exists photos_private_authenticated_update on storage.objects;

-- photos-public: anon + authenticated may READ (the bucket is public-marked).
-- No INSERT / UPDATE / DELETE policy for client roles. service_role manages
-- contents from the Edge Functions.

drop policy if exists photos_public_anon_read on storage.objects;
drop policy if exists photos_public_authenticated_read on storage.objects;
drop policy if exists photos_public_authenticated_write on storage.objects;

create policy photos_public_anon_read
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'photos-public');

-- Optional: editors may LIST objects in photos-private to help debug uploads.
-- Disabled by default; uncomment if needed and audit before enabling.
--
-- create policy photos_private_editors_read
--   on storage.objects
--   for select
--   to authenticated
--   using (
--     bucket_id = 'photos-private'
--     and coalesce(public.snh_member_has_photos_admin_access(), false)
--   );

-- NOTE: We deliberately do NOT run `COMMENT ON POLICY ... ON storage.objects`
-- here. storage.objects is owned by supabase_storage_admin; the migration
-- role can CREATE / DROP policies on it (Supabase grants those explicitly)
-- but cannot COMMENT on it (Postgres requires table ownership for COMMENT).
-- The rationale that would have been the policy comment:
--   Read-only public access to derivative objects in photos-public.
--   Writes only via service_role from photo Edge Functions.
